#!/bin/bash
gcc -std=gnu99 -Wall -Wextra -Wpedantic -Werror -o enc_server enc_server.c
gcc -std=gnu99 -Wall -Wextra -Wpedantic -Werror -o enc_client enc_client.c
gcc -std=gnu99 -Wall -Wextra -Wpedantic -Werror -o dec_server dec_server.c
gcc -std=gnu99 -Wall -Wextra -Wpedantic -Werror -o dec_client dec_client.c
gcc -std=gnu99 -Wall -Wextra -Wpedantic -Werror -o keygen keygen.c
